
spring.datasource.url=jdbc:mysql://localhost:3306/bllogberiferico
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
jwt.secret=6Z0y4LkXv5cQ2YxKelW-jdP9d6R4KbU8D2fhoX1G2C8=
jwt.expiration=3600000